### ISSUE TITLE
Region -> region in summaryData

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/RtD3#14]
It might be cleaner to make `summaryData` require the same region name as the other datasets.`EpiNow2` estimates could then be adapted to fit to this in `readInEpiNow2`.

**Comment by hamishgibbs** [comment]
Handled in `rt_vis` just needs to be handled in `check_input_data`

**Comment by hamishgibbs** [comment]
New version of `rt_vis` not added here yet - I will handle when other changes done
