### ISSUE TITLE
widget not always showing up in html when rendered from Rmd

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/RtD3#15]
Not sure if this a `RtD3` issue but when trying to render multiple widgets across multiple Rmds seeing that some are not rendering. When rerendered they render successfully. Any ideas?

**Comment by seabbs** [comment]
No longer seeing this......  and have been unable to replicate. Suggest close unless you think this is real @hamishgibbs?

**Comment by hamishgibbs** [comment]
Agree to close. May be an issue with downloading some crucial input data that is passed null and makes the widget render blank? Not sure. Sounds good to close
