### ISSUE TITLE
Adding new/multiple CrI ribbons

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/RtD3#16]
An update to EpiNow2 has added a 20% HDI ribbon (see readme https://github.com/epiforecasts/EpiNow2). Might make sense to take this time to make the number of ribbons be generalizable in some way? Or perhaps just add this new ribbon to the vis.

**Comment by hamishgibbs** [comment]
This is a job for `rt_vis` so I have opened:

https://github.com/hamishgibbs/rt_vis/issues/19

Going to close here.

**Comment by seabbs** [comment]
(you can move issues between repos you control :))

**Comment by hamishgibbs** [comment]
Woah. Had no idea
