### ISSUE TITLE
tsWidget

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/RtD3#19]

**Comment by hamishgibbs** [comment]
Function to produce only ts plots. Related to #9

**Comment by hamishgibbs** [comment]
@seabbs this could do the work of creating the top n widgets you have as static facets in the current site?

Will just have to work out how to get them to share the same layout best. 

![image](https://user-images.githubusercontent.com/50525951/93599530-2b0f2b80-f9b6-11ea-8c6f-4222d32d0c2d.png)

**Comment by seabbs** [comment]
That would be very neat. Especially if you can have some kind of selection criteria (so show 1 plot that can be Rt, cases etc and then change which countries are shown....). Very cool.

**Comment by hamishgibbs** [comment]
`tsWidget` is now in place but creating the above widget is probably a job in `rt_vis`, not `RtD3`. I have opened #26 and will close this.
