### ISSUE TITLE
Question: function names

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/RtD3#27]
We are calling a lot of things widgets which isn't my favourite word to say or type.

The name of the function doesn't have anything to do with the underlying JavaScript so we could change names to something more R-thonic?

like `rt_dashboard` instead of `summaryWidget`? 

Just a thought - happy to hear your thoughts as you already have the package implemented somewhere @seabbs.

**Comment by seabbs** [comment]
yes, good point. Probably don't need to include `rt` in the name as already part of the package name though (which is something I like about the current naming scheme actually). In general supportive of a naming change but not clear to what. 

It could be as simple as (obviously using Camel case): 

```
RtD3::dashboard()

RtD3::plot_timeseries()

RtD3::plot_timepoint()
```

I will just need a bit of warning if this happens so I don't update `RtD3` where the website gets updated until all the uses are also updated.

**Comment by seabbs** [comment]
action on this or close?

**Comment by hamishgibbs** [comment]
Close for now. Package is working fine and we can make these changes if they are required in the future.
