### ISSUE TITLE
pkgdown action failing

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/RtD3#37]
Looks like building docs with pkgdown is failing because of an issue with dependencies in the development version of pkgdown?

Is there a reason to install the development version and not the CRAN version?

https://github.com/epiforecasts/RtD3/blob/a1b851f8064e1bac2cf1ecccd11e08c8030b523b/.github/workflows/pkgdown.yaml#L42

**Comment by hamishgibbs** [comment]
@seabbs

**Comment by seabbs** [comment]
Hmm odd - should be fixed by bug patch to master adding in some more linux deps. 

So they tend to be fairly slow at releasing to CRAN so having the dev version gives you much nicer-looking docs. Its very rare they push breaking changes to master in my experience.

**Comment by hamishgibbs** [comment]
Looks like this is sorted and docs are rebuilding correctly. Closing.
