### ISSUE TITLE
Time series failing to plot

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/RtD3#39]
India time series are failing to plot because of an issue with the `ts_color_ref` being passed from summaryWidget. I will see if I can replicate the error locally and then we can figure out how to fix it.

See: https://epiforecasts.io/covid/posts/national/india/

**Comment by hamishgibbs** [comment]
@seabbs

**Comment by seabbs** [comment]
Its fine in your docs: https://epiforecasts.io/RtD3/articles/subnational.html

Hmm - checking india implementation on the site for other problems.

**Comment by hamishgibbs** [comment]
Ok - when I create the dashboard locally - I get all the colors and it works fine. 

Here is the error being thrown:

<img width="517" alt="Screenshot 2020-10-05 at 10 09 46" src="https://user-images.githubusercontent.com/50525951/95090195-fe1b8200-06f2-11eb-8d14-72d001525dce.png">

This is caused by an incorrectly formatted `ts_color_ref` which is defined here: 

https://github.com/epiforecasts/RtD3/blob/70512d7cbd426c6efd7c2f93a85b08aa4ab95ce1/R/default_ts_colors.R#L11-L19

And passed to `rt_vis` as `ts_color_ref` here: 

https://github.com/epiforecasts/RtD3/blob/70512d7cbd426c6efd7c2f93a85b08aa4ab95ce1/R/summaryWidget.R#L60

**Comment by hamishgibbs** [comment]
Because the color_ref is a default and should be defined automatically - I am not sure where the issue is coming from atm

**Comment by seabbs** [comment]
I looked through the site implementation and I can't see anything. My thought is that maybe the update to `rtD3` hit mid way through the rendering of the india page so it bugged out. I'll check the update in 2 hours and close if this goes away.

**Comment by hamishgibbs** [comment]
That is a strong possibility. Sounds good.

**Comment by seabbs** [comment]
oooops :)

**Comment by hamishgibbs** [comment]
Looks like this was solved by waiting for everything to update. Going to close.
