### ISSUE TITLE
Widget - bottom text collision

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/RtD3#43]
Text is colliding with the bottom of the widget. Need to increase the default height in:

https://github.com/epiforecasts/RtD3/blob/8a2f13b77dab0da795f5e522f71fc2a2d4ebf075/R/define_height.R#L15-L19

Issue comes from the changes to `rt_vis` which added some more padding to the time series legend container. 

![Screenshot 2020-10-16 at 14 57 03](https://user-images.githubusercontent.com/50525951/96298228-1d9e8e80-0fc0-11eb-8076-cf80e06a1857.png)

**Comment by seabbs** [comment]
Are these default heights based on an inspection of Rmds? If that is the case not sure I can think of another approach.

**Comment by hamishgibbs** [comment]
Yeah - the height (in pixels) of the widget is default but the width is variable. Just need to bump 225px (or the following 100px) to accommodate the new default height. I will open a PR promptly.
