### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/RtD3#5]
Having to update the docs locally made me very sad. Its cool to use GitHub actions to do this. There are some examples in `EpiNow2/.github/workflows` and am happy to explain (all needs to be done on master).

**Comment by seabbs** [comment]
Done in #32

**Comment by hamishgibbs** [comment]
I believe this was handled by #32 and can be closed?

**Comment by seabbs** [comment]
yes!
